"""Perguntas iniciais de cada etapa, baseadas no modelo de PEI do NAPNE/IFRN.

Podem ser alteradas, incluídas ou excluídas pela tela de Administração.
Campos: etapa, secao, enunciado, tipo, opcoes, obrigatoria, texto_nada, ajuda.
"""

SIM_NAO = ["Sim", "Não"]

PERGUNTAS = [
    # ------------------------------------------------------------------ PSICOPEDAGOGIA
    dict(etapa="psicopedagogia", secao="Necessidades educacionais específicas",
         enunciado="Necessidades educacionais específicas identificadas",
         tipo="checkbox",
         opcoes=["Transtorno do Espectro Autista (TEA)",
                 "Transtorno de Déficit de Atenção e Hiperatividade (TDAH)",
                 "Transtorno de Ansiedade Generalizada (TAG)",
                 "Dislexia", "Discalculia", "Disgrafia / Disortografia",
                 "Deficiência intelectual", "Deficiência visual (baixa visão)", "Cegueira",
                 "Deficiência auditiva / Surdez", "Deficiência física",
                 "Altas habilidades / Superdotação", "Outra (descrever abaixo)"]),
    dict(etapa="psicopedagogia", secao="Necessidades educacionais específicas",
         enunciado="Situação da documentação clínica (laudo)",
         tipo="radio",
         opcoes=["Possui laudo", "Em investigação diagnóstica", "Sem laudo, com indicativos observados"]),
    dict(etapa="psicopedagogia", secao="Necessidades educacionais específicas",
         enunciado="Laudos, CID e profissionais que emitiram os documentos",
         tipo="longa", obrigatoria=False,
         ajuda="Informe CID(s), data dos laudos e profissionais/serviços de origem.",
         texto_nada="Não foram apresentados laudos ou documentos clínicos ao NAPNE até o momento."),
    dict(etapa="psicopedagogia", secao="Necessidades educacionais específicas",
         enunciado="Acompanhamentos especializados externos",
         tipo="checkbox",
         opcoes=["Psicologia", "Psiquiatria", "Neurologia", "Fonoaudiologia",
                 "Terapia ocupacional", "Psicopedagogia clínica", "Nenhum"]),
    dict(etapa="psicopedagogia", secao="Avaliação psicopedagógica",
         enunciado="Aspectos cognitivos e de aprendizagem (atenção, memória, raciocínio, leitura, escrita, cálculo)",
         tipo="longa",
         texto_nada="O(A) estudante não apresentou alterações relevantes nos aspectos cognitivos e de aprendizagem que demandem acompanhamento especializado nesta dimensão."),
    dict(etapa="psicopedagogia", secao="Avaliação psicopedagógica",
         enunciado="Aspectos emocionais e comportamentais",
         tipo="longa",
         texto_nada="O(A) estudante não apresentou necessidade de acompanhamento especializado quanto aos aspectos emocionais e comportamentais."),
    dict(etapa="psicopedagogia", secao="Avaliação psicopedagógica",
         enunciado="Comunicação e interação social",
         tipo="longa",
         texto_nada="O(A) estudante não apresentou dificuldades de comunicação ou interação social que demandem acompanhamento especializado."),
    dict(etapa="psicopedagogia", secao="Avaliação psicopedagógica",
         enunciado="Aspectos sensoriais e motores",
         tipo="longa",
         texto_nada="Não foram identificadas necessidades sensoriais ou motoras que demandem adaptações específicas."),
    dict(etapa="psicopedagogia", secao="Avaliação psicopedagógica",
         enunciado="Recomendações psicopedagógicas à equipe e aos docentes",
         tipo="longa",
         texto_nada="Não há recomendações psicopedagógicas específicas além das práticas pedagógicas regulares."),

    # ------------------------------------------------------------------ ETEP
    dict(etapa="etep", secao="Histórico",
         enunciado="Histórico escolar e dos atendimentos realizados após a matrícula",
         tipo="longa",
         ajuda="Inserir informações sobre os atendimentos realizados após a matrícula na instituição e, se necessário, ao longo do período letivo.",
         texto_nada="Não há registros de atendimentos pedagógicos anteriores ao presente PEI."),
    dict(etapa="etep", secao="Perfil pedagógico",
         enunciado="Conhecimentos, habilidades, capacidades e interesses (o que sabe? do que gosta? afinidades?)",
         tipo="longa",
         texto_nada="Não foram registrados conhecimentos, habilidades ou interesses específicos até o momento."),
    dict(etapa="etep", secao="Perfil pedagógico",
         enunciado="Dificuldades apresentadas",
         tipo="longa",
         texto_nada="O(A) estudante não apresentou dificuldades pedagógicas significativas até o momento."),
    dict(etapa="etep", secao="Apoios e recursos",
         enunciado="Apoios e recursos de acessibilidade recomendados",
         tipo="checkbox",
         opcoes=["Atendimento individualizado (Centro de Aprendizagem)", "Monitoria",
                 "Tempo adicional em avaliações", "Avaliação em ambiente separado",
                 "Ledor / Transcritor", "Intérprete de Libras", "Material ampliado",
                 "Material impresso", "Tecnologia assistiva", "Nenhum"]),
    dict(etapa="etep", secao="Apoios e recursos",
         enunciado="Participação da família no acompanhamento escolar",
         tipo="select",
         opcoes=["Participativa", "Parcialmente participativa", "Pouco participativa",
                 "Não foi possível contato", "Não se aplica (estudante maior de idade)"]),
    dict(etapa="etep", secao="Apoios e recursos",
         enunciado="Estratégias pedagógicas recomendadas aos docentes",
         tipo="longa",
         texto_nada="Não há estratégias pedagógicas específicas recomendadas além das práticas regulares de ensino."),
    dict(etapa="etep", secao="Apoios e recursos",
         enunciado="Observações gerais sobre outras necessidades educacionais específicas do(a) estudante",
         tipo="longa", obrigatoria=False,
         texto_nada="Nada a declarar sobre outras necessidades educacionais específicas do(a) estudante."),

    # ------------------------------------------------------------------ DOCENTE (por componente)
    dict(etapa="docente", secao="Objetivos",
         enunciado="Objetivos do componente curricular (conforme PPC)",
         tipo="longa", ajuda="Verifique no PPC do curso os objetivos da disciplina.",
         texto_nada="Objetivos conforme o PPC do curso, sem detalhamento adicional."),
    dict(etapa="docente", secao="Objetivos",
         enunciado="Os objetivos precisaram ser adaptados para o(a) estudante?",
         tipo="radio", opcoes=SIM_NAO),
    dict(etapa="docente", secao="Objetivos",
         enunciado="Adaptações realizadas nos objetivos",
         tipo="longa",
         texto_nada="Os objetivos do componente curricular não precisaram ser adaptados para o(a) estudante."),
    dict(etapa="docente", secao="Conteúdos programáticos",
         enunciado="Conteúdos programáticos (conforme PPC)",
         tipo="longa",
         texto_nada="Conteúdos programáticos conforme o PPC do curso, sem detalhamento adicional."),
    dict(etapa="docente", secao="Conteúdos programáticos",
         enunciado="Adaptações realizadas nos conteúdos",
         tipo="longa",
         texto_nada="Os conteúdos do componente curricular não precisaram ser adaptados para o(a) estudante."),
    dict(etapa="docente", secao="Metodologias",
         enunciado="Estratégias metodológicas comumente utilizadas",
         tipo="checkbox",
         opcoes=["Aulas expositivas dialogadas", "Exercícios práticos", "Projetos",
                 "Aulas em laboratório", "Trabalhos em grupo", "Seminários",
                 "Estudos dirigidos", "Sala de aula invertida"]),
    dict(etapa="docente", secao="Metodologias",
         enunciado="Metodologias específicas adotadas para o(a) estudante (atendimentos individuais, etc.)",
         tipo="longa",
         texto_nada="Não foram necessárias metodologias específicas para o(a) estudante neste componente."),
    dict(etapa="docente", secao="Recursos didáticos",
         enunciado="Recursos didáticos comumente utilizados",
         tipo="checkbox",
         opcoes=["Quadro branco", "Computador", "Laboratório", "Projetor multimídia",
                 "Vídeos", "Material impresso", "Ambiente virtual (Moodle/Classroom)"]),
    dict(etapa="docente", secao="Recursos didáticos",
         enunciado="Adaptações nos recursos didáticos",
         tipo="longa",
         texto_nada="Não houve necessidade de adaptação dos recursos didáticos para o(a) estudante."),
    dict(etapa="docente", secao="Avaliações",
         enunciado="Instrumentos de avaliação comumente utilizados",
         tipo="checkbox",
         opcoes=["Prova escrita", "Prova prática", "Listas de exercícios", "Projetos",
                 "Seminários", "Trabalhos em grupo", "Participação nas aulas"]),
    dict(etapa="docente", secao="Avaliações",
         enunciado="Adaptações nas avaliações (tipo de avaliação diferenciado, tempo de prova, etc.)",
         tipo="longa",
         texto_nada="Não houve necessidade de adaptação nos instrumentos ou nas condições de avaliação."),
    dict(etapa="docente", secao="Comportamento em sala de aula",
         enunciado="Relação com colegas e professores",
         tipo="select", opcoes=["Boa", "Regular", "Com dificuldades", "Não observada"]),
    dict(etapa="docente", secao="Comportamento em sala de aula",
         enunciado="Comportamento, participação e engajamento em sala de aula",
         tipo="longa",
         texto_nada="O(A) estudante não apresentou comportamentos em sala de aula que demandem acompanhamento específico."),
    dict(etapa="docente", secao="Parecer do docente",
         enunciado="Parecer: trajetória do(a) estudante no componente, habilidades, dificuldades, adaptações e percepções sobre a aprendizagem",
         tipo="longa",
         texto_nada="O(A) estudante apresenta bom acompanhamento do componente, sem necessidade de adaptações curriculares, metodológicas ou avaliativas."),
    dict(etapa="docente", secao="Parecer do docente",
         enunciado="Situação atual no componente curricular",
         tipo="select",
         opcoes=["Em andamento", "Aprovado(a)", "Reprovado(a)", "Em recuperação / dependência"]),

    # ------------------------------------------------------------------ GESTÃO (revisão)
    dict(etapa="gestao", secao="Registro do acompanhamento do PEI",
         enunciado="Registro do acompanhamento do PEI",
         tipo="longa", obrigatoria=False,
         texto_nada="Nada a declarar quanto ao acompanhamento do PEI neste período."),
    dict(etapa="gestao", secao="Parecer da equipe multiprofissional",
         enunciado="Parecer da equipe multiprofissional",
         tipo="longa",
         texto_nada="A equipe multiprofissional ratifica as informações e adaptações registradas neste PEI, sem observações adicionais."),
]
